name: Testing
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  unit-ui-testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    
    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node-version }}
      - name: install packages
        run: npm install
      - name: build prod
        run: npx run build:prod
      - name: lint TS files
        run: npx run lint:ts
      - name: lint CSS files
        run: npx run lint:scss
      - name: unit test
        run: npx run test:unit